### ISSUE TITLE
Bug Unknown users in stats

### ISSUE THREAD

**Issue by Paddewan** [aigeroni/Winnie_Bot#108]
**Describe the bug**
Some of our people get mentioned as Unknown User, no longer their name.  This happens in the stats as in the !list when making a war with no name.  It seems the names that are switched with unknown user are not always the same names.  

**Command Syntax Used**
!raptors

**Expected behavior**
The names to be shown in the list.

**Screenshots**
A screenshot of the Discord chat showing the command that was entered, and the unexpected behaviour that Winnie exhibited.
![image](https://user-images.githubusercontent.com/73948367/98120388-2c38e100-1eae-11eb-9669-774583cbf3cf.png)

**Additional context**

**Comment by jegillikin** [comment]
We (Nano OCGR) experience this same problem, under the same circumstances, with any user who executes !raptors -- regardless of permissions. The problem seemed to begin in the very early morning hours of 04 Nov.

**Comment by lisushka** [comment]
This is due to the restart that was required to clear a recurrence of the channel deletion bug, and Discord's recent changes to presence data.  There's nothing I can do about it, but as users interact with Winnie again, she'll be able to recognise their names.
