### ISSUE TITLE
Challenge feature stopped working, 22 Nov 17:05 GMT

### ISSUE THREAD

**Issue by jegillikin** [aigeroni/Winnie_Bot#126]
(Likely a duplicate of #106 but reporting for visibility given that challenges stopped working before the **!list** command stopped responding.)

**DESCRIPTION:**
Winnie's challenge features failed around 2:05 to 2:10 p.m. EST (-5 GMT). For a while, new challenges added but Winnie failed to respond with status messages and the **!list** function worked; not long thereafter (by 2:30), the **!list** command stopped responding as well. Goals and Raptors still work as expected.

**SYNTAX:**
**!List**

**EXPECTED BEHAVIOR:**
Challenges continue on their timers and display correctly.

**SCREENSHOTS:**
![image](https://user-images.githubusercontent.com/7763031/99915276-c5e6f780-2cd0-11eb-8751-2fa442caba1d.png)

**ADDITIONAL CONTEXT:**
Starting with 40425, all start timers default to whole-minute increments rather than minute-second increments.

**Comment by lisushka** [comment]
Actually due to our friend #94 again.  It's well and truly top of the list for December.
