### ISSUE TITLE
Bug: Goal raptor not granted despite meeting goal

### ISSUE THREAD

**Issue by KerrynM** [aigeroni/Winnie_Bot#92]
**Describe the bug**
Winnie did not allocate a raptor for achieving daily goal.

**Command Syntax Used**
It was Winnie's error, 

**Expected behavior**
A raptor to be given at midnight for completion of daily goal. 

**Screenshots**
A screenshot of the Discord chat showing the command that was entered, and the unexpected behaviour that Winnie exhibited.
OT
 Winnie_Bot: @KerrynM, your total of 20 minutes has been added to the summary.
@KerrynM, you have written 40 minutes of your 40-minute goal.
OT
 [12:00 AM]Winnie_Bot: @ArtMasque, you have hatched a raptor! Your server currently houses 1464 raptors.
[6:27 AM] KerrynM: What happened Winnie to my goal raptor??

**Additional context**

**Comment by lisushka** [comment]
This appears to be a genuine bug, and is possibly infrastructure-related.  I'll look into it.
