### ISSUE TITLE
Bug: Entering an invalid goal when attempting to reset discards the previous goal

### ISSUE THREAD

**Issue by writingwip** [aigeroni/Winnie_Bot#95]
**Describe the bug**
1-Winnie dropped a users goal and progress of their goal on 26/7 (MelbNaNo)
2 - On multiple days the midnight raptors have had two notifications sent to the same user (there was no double raptor given, just two notifs) (MelbNaNo)

**Command Syntax Used**
The exact command that you entered to produce the error.
1 - !reset 60 minutes
2 - none, Winnie's code awards midnight raptors in each timezone

**Expected behavior**
1. A reset and change of the user's daily goal
2. A singular notification awarding one raptor per user each night

**Screenshots**
A screenshot of the Discord chat showing the command that was entered, and the unexpected behaviour that Winnie exhibited.
1 - 
![image](https://user-images.githubusercontent.com/68898894/88652445-3492ba80-d10e-11ea-8b0b-00bbae4d78a8.png)
2 - 
![image](https://user-images.githubusercontent.com/68898894/88652841-af5bd580-d10e-11ea-9095-644d39577bb7.png)

**Additional context**

**Comment by lisushka** [comment]
The second issue is likely an API glitch and doesn't actually award multiple raptors, it just causes the message to display twice.  Can you please provide a screenshot of your first attempt at setting a goal on 2020-07-26 so that I can verify this as an issue?

**Comment by writingwip** [comment]
Yeah - we thought it was just a glitch. 

The original set goal on 26/7: https://cdn.discordapp.com/attachments/486769349923962890/737617116773220383/Screen_Shot_2020-07-28_at_8.26.21_pm.png

**Comment by writingwip** [comment]
And an update to the original goal a few minutes before the reset: 
https://cdn.discordapp.com/attachments/486769349923962890/737617658887012412/Screen_Shot_2020-07-28_at_8.28.38_pm.png

**Comment by lisushka** [comment]
I know what the cause of this is and will look into it when I have time.

**Comment by writingwip** [comment]
Okay. Thank you
