### ISSUE TITLE
Raptor counts reset

### ISSUE THREAD

**Issue by jegillikin** [aigeroni/Winnie_Bot#97]
We discovered that in the process of re-configuring some of our server bots, that our raptor count has been reset to zero. (Now two, thanks to my testing.) In the grand scheme of things, it's a small deal, but it was a point of pride that our server (NaNo OCGR) had been in the top five or six servers. Now we're down to No. 34.

Is it possible to get a manual reset? Or are we just screwed? And can you share what scenarios would prompt a reset like this, so we can avoid it again in the future?

**Comment by lisushka** [comment]
I'm currently in the process of migrating the database from one engine to another.  As part of this process, the raptor counts are going to reset once every couple of months or so, as migrating the actual data in the database would be a significantly more complicated task.

The ultimate aim is to have the raptors reset every year in late October, while maintaining a lifetime count.  However, this won't be possible until the database engine is stable.
